// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1, arg2) {
  return window['go']['app']['App']['AddTag'](arg1, arg2);
}

export function AddToAlbum(arg1, arg2) {
  return window['go']['app']['App']['AddToAlbum'](arg1, arg2);
}

export function AlbumFromDir(arg1) {
  return window['go']['app']['App']['AlbumFromDir'](arg1);
}

export function ApplyChanges() {
  return window['go']['app']['App']['ApplyChanges']();
}

export function ApplyOrganize(arg1) {
  return window['go']['app']['App']['ApplyOrganize'](arg1);
}

export function CheckChanges() {
  return window['go']['app']['App']['CheckChanges']();
}

export function ClearThumbs() {
  return window['go']['app']['App']['ClearThumbs']();
}

export function CloseLibrary() {
  return window['go']['app']['App']['CloseLibrary']();
}

export function CreateAlbum(arg1) {
  return window['go']['app']['App']['CreateAlbum'](arg1);
}

export function DeleteAlbum(arg1) {
  return window['go']['app']['App']['DeleteAlbum'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['app']['App']['DeleteTag'](arg1);
}

export function Duplicates() {
  return window['go']['app']['App']['Duplicates']();
}

export function EmptyTrash() {
  return window['go']['app']['App']['EmptyTrash']();
}

export function ExportJSON() {
  return window['go']['app']['App']['ExportJSON']();
}

export function GetDetail(arg1) {
  return window['go']['app']['App']['GetDetail'](arg1);
}

export function GetOverview() {
  return window['go']['app']['App']['GetOverview']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function List(arg1) {
  return window['go']['app']['App']['List'](arg1);
}

export function MergeTakeout() {
  return window['go']['app']['App']['MergeTakeout']();
}

export function MoveFiles(arg1, arg2) {
  return window['go']['app']['App']['MoveFiles'](arg1, arg2);
}

export function OpenLibrary(arg1) {
  return window['go']['app']['App']['OpenLibrary'](arg1);
}

export function PickFolder() {
  return window['go']['app']['App']['PickFolder']();
}

export function PlanOrganize(arg1) {
  return window['go']['app']['App']['PlanOrganize'](arg1);
}

export function RemoveFromAlbum(arg1, arg2) {
  return window['go']['app']['App']['RemoveFromAlbum'](arg1, arg2);
}

export function RemoveTag(arg1, arg2) {
  return window['go']['app']['App']['RemoveTag'](arg1, arg2);
}

export function RenameAlbum(arg1, arg2) {
  return window['go']['app']['App']['RenameAlbum'](arg1, arg2);
}

export function RestoreFiles(arg1) {
  return window['go']['app']['App']['RestoreFiles'](arg1);
}

export function Reveal(arg1) {
  return window['go']['app']['App']['Reveal'](arg1);
}

export function SetDate(arg1, arg2) {
  return window['go']['app']['App']['SetDate'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function TakeoutSummary() {
  return window['go']['app']['App']['TakeoutSummary']();
}

export function TrashFiles(arg1) {
  return window['go']['app']['App']['TrashFiles'](arg1);
}

export function Undo() {
  return window['go']['app']['App']['Undo']();
}
