// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {store} from '../models';
import {library} from '../models';

export function AddTag(arg1:Array<number>,arg2:string):Promise<void>;

export function AddToAlbum(arg1:number,arg2:Array<number>):Promise<void>;

export function AlbumFromDir(arg1:string):Promise<number>;

export function ApplyChanges():Promise<void>;

export function ApplyOrganize(arg1:string):Promise<number>;

export function CheckChanges():Promise<app.ChangeReport>;

export function ClearThumbs():Promise<void>;

export function CloseLibrary():Promise<void>;

export function CreateAlbum(arg1:string):Promise<number>;

export function DeleteAlbum(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function Duplicates():Promise<Array<any>>;

export function EmptyTrash():Promise<number>;

export function ExportJSON():Promise<string>;

export function GetDetail(arg1:number):Promise<app.Detail>;

export function GetOverview():Promise<app.Overview>;

export function GetState():Promise<app.State>;

export function List(arg1:store.Filter):Promise<store.Page>;

export function MergeTakeout():Promise<library.TakeoutResult>;

export function MoveFiles(arg1:Array<number>,arg2:string):Promise<number>;

export function OpenLibrary(arg1:string):Promise<app.State>;

export function PickFolder():Promise<app.State>;

export function PlanOrganize(arg1:string):Promise<app.OrganizePreview>;

export function RemoveFromAlbum(arg1:number,arg2:Array<number>):Promise<void>;

export function RemoveTag(arg1:Array<number>,arg2:number):Promise<void>;

export function RenameAlbum(arg1:number,arg2:string):Promise<void>;

export function RestoreFiles(arg1:Array<number>):Promise<number>;

export function Reveal(arg1:number):Promise<void>;

export function SetDate(arg1:Array<number>,arg2:number):Promise<library.DateResult>;

export function SetLanguage(arg1:string):Promise<app.State>;

export function TakeoutSummary():Promise<library.TakeoutSummary>;

export function TrashFiles(arg1:Array<number>):Promise<number>;

export function Undo():Promise<number>;
